export const PATHS = {
  HOME: '/',
  PROFILE: '/profile',
  TASKS: '/tasks',
  DIARY_WEEKS: '/diary-weeks',
  DIARY_INPUT: '/diary-input/:id',
  NOTIFICATIONS: '/notifications',
  NEWS: '/news',
  SETTINGS: '/settings',
  LOGIN: '/login',
  CHANGE_PASSWORD: '/change-password',
  EDIT_TASKS: '/edit-tasks',
  TERMS: '/terms',
  VIOLATIONS: '/violations',
  ACHIEVEMENTS: '/achievements',
  GRANT_PERMISSION: '/grant-permission',
  VIOLATION_WEEKS: '/violation-weeks',
  VIOLATION_INPUT: '/violation-input/:id',
  CALCULATE_GPA: '/calculate-gpa',
  SURVEYS: '/surveys',
  SURVEY_TAKE: '/survey-take/:id',
  DUTY_WEEKS: '/duty-weeks',
  DUTY_INPUT: '/duty-input/:id',
  WEEKLY_RESULTS: '/ket-qua-tuan',
  EXAM_SCHEDULE: '/lich-hoc-thi',
  EXAM_SCORES: '/diem-thi',
  EXAM_APPEAL: '/phuc-khao',
  EMAIL_STUDENT: '/email-hoc-sinh',
  ACTIVITIES: '/hoat-dong',
  ACTIVITY_DETAIL: '/hoat-dong/:id',
  LEAVE_REQUESTS: '/xin-vang-hoc',
  LEAVE_REQUEST_CREATE: '/xin-vang-hoc/tao-moi',
} as const;

export const TAB_PATHS: Record<string, string> = {
  home: PATHS.HOME,
  profile: PATHS.PROFILE,
  tasks: PATHS.TASKS,
  notification: PATHS.NOTIFICATIONS,
  setting: PATHS.SETTINGS,
};

export const PATH_TO_TAB: Record<string, string> = {
  [PATHS.HOME]: 'home',
  [PATHS.PROFILE]: 'profile',
  [PATHS.TASKS]: 'tasks',
  [PATHS.NOTIFICATIONS]: 'notification',
  [PATHS.SETTINGS]: 'setting',
};
